// <auto-generated />
using System;
using ItemApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ItemApp.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20210404110951_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("ItemApp.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Author1",
                            Content = "Content1",
                            CreatedAt = new DateTime(2021, 4, 4, 20, 9, 51, 420, DateTimeKind.Local).AddTicks(1739),
                            Title = "Title1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Author2",
                            Content = "Content2",
                            CreatedAt = new DateTime(2021, 4, 4, 20, 9, 51, 421, DateTimeKind.Local).AddTicks(3466),
                            Title = "Title2"
                        });
                });

            modelBuilder.Entity("ItemApp.Models.SubItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("SubItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "SubAuthor1",
                            CreatedAt = new DateTime(2021, 4, 4, 20, 9, 51, 422, DateTimeKind.Local).AddTicks(2261),
                            ItemId = 1,
                            SubContent = "SubContent1",
                            SubTitle = "SubTitle1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "SubAuthor2",
                            CreatedAt = new DateTime(2021, 4, 4, 20, 9, 51, 422, DateTimeKind.Local).AddTicks(2923),
                            ItemId = 2,
                            SubContent = "SubContent2",
                            SubTitle = "SubTitle2"
                        });
                });

            modelBuilder.Entity("ItemApp.Models.SubItem", b =>
                {
                    b.HasOne("ItemApp.Models.Item", "Item")
                        .WithMany("SubItems")
                        .HasForeignKey("ItemId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ItemApp.Models.Item", b =>
                {
                    b.Navigation("SubItems");
                });
#pragma warning restore 612, 618
        }
    }
}
